### PR TITLE
Valid features

### PR DESCRIPTION
**Pull request by Iamgoofball**
muh merge conflicts

### CODE REVIEW

**Comment by Iamgoofball** [comment]
alright so your branch was slightly out of date so that's why there a shitton of extra commits

mine was more up to date

the actual commit to look at is: https://github.com/Iamgoofball/-tg-station/commit/b210a9718834adcdcb814fba4ab3641dce3a0937

**Comment by JJRcop** [comment]
This is why it's better to fetch their specific branch, and work off that, but that isn't as convenient
The correct git commands to use in this instance are
```
git fetch https://github.com/Xhuis/-tg-station.git the_shittening
git checkout FETCH_HEAD
git checkout -b valid_features
```
Copy-pastable version
```git fetch https://github.com/Xhuis/-tg-station.git the_shittening; git checkout FETCH_HEAD; git checkout -b valid_features;```

**Comment by Xhuis** [comment]
While I want to implement this immediately, my better judgement goes against it. I want the implementation to be mainly funny, not inherently problem-causing like high explosive turrets.

The mentorhelp, clown cube box, and syndicate pie seem fine, but I'd rather the others were removed or at least commented out. I'll see what I can do on my end to get the huge amount of file changes fixed.

**Comment by Iamgoofball** [comment]
@Xhuis what do you have against emagging emags?

**Comment by Xhuis** [comment]
All-access IDs

**Comment by Iamgoofball** [comment]
changes made

**Comment by Xhuis** [comment]
Mkay, should be no issues with the files changed but if there is I'll revert

**Pull request merged**
